"use strict";

/* Shared application state */

const state = {
    els: null,
    stream: null,
    track: null,
    devices: [],
    activeDeviceId: "",
    detector: null,
    scanner: null,
    scannerEngine: "",
    isCameraRunning: false,
    isScanning: false,
    torchOn: false,
    scanTimer: 0,
    authCookie: "",
    authStatus: "",
    history: [],
    selectedHistoryIndex: -1,
    pendingConfirmAction: null,
    currentProductRecord: null,
    editingHistoryId: "",
    fieldEls: {},
    lastStatusMessage: "",
    isMobileUi: false,
    isScanLoopScheduled: false,
    isScanInFlight: false,
    audioContext: null,
    toastTimer: 0,
    previewWatchdogTimer: 0,
    lastPreviewTime: 0,
    stalledPreviewChecks: 0,
    isRecoveringPreview: false,
    lookupSequence: 0,
    displayMode: "full",
    isQuantityEntryUnlocked: false,
    lockedScrollY: 0,
    pendingApiRequests: 0,
    inputMode: "phone",
    manualScrollLocked: false,
    manualScrollLockY: 0,
    cameraStartPromise: null,
    focusRefreshTimers: [],
    iosWarmRestartDone: false,
    isIOS: false,
    captureContext: null,
    lastDetectedBarcode: "",
    lastDetectedAt: 0,
    scanAnimationFrame: 0,
    resumePreviewTimer: 0,
    closestSearchResults: [],
    closestSearchCode: "",
    closestSearchPendingHistoryId: "",
    isClosestSearchLoading: false,
    historyEditSuccessTimer: 0,
    historyEditCloseTimer: 0,
    roi: { width: 0.8, height: 0.8 },
    roiDrag: null,
    pendingConfirmCode: "",
    pendingConfirmCount: 0
  };
